name: DenizEkosistemi
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  path_provider: ^2.1.4
  just_audio: ^0.9.42
  just_audio_windows: ^0.2.2
  easy_url_launcher: ^0.0.7
  font_awesome_flutter: ^10.3.0
  google_fonts: ^6.2.1
  theme_mode_builder: ^2.0.0
  share_plus: ^10.0.2
  salomon_bottom_bar: ^3.3.2
  http: ^1.2.2
  package_info_plus: ^8.0.2
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  flutter_animate: ^4.5.2

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: {
    "generate": true
  }
  web: {
    "generate": true
  }
  windows: {
    "generate": true
  }
  image_path: "assets/anaicon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/sesler/