import 'package:DenizEkosistemi/util.dart';
import 'package:http/http.dart' as http;

class Ulkeler {
  String bayrak, enisim, isim, baskent, kita, url;
  bool bilgi, bm;
  double enlem, boylam;
  int dosyaboyut;

  Ulkeler({
    required this.bayrak,
    required this.enisim,
    required this.isim,
    required this.baskent,
    required this.kita,
    required this.url,
    required this.bilgi,
    required this.bm,
    required this.enlem,
    required this.boylam,
    required this.dosyaboyut,
  });
}
class Yazi {
  static Map<String, dynamic>? _localizedStrings;
  static String _currentLanguage = 'Türkçe';

  // Dil dosyasını yükler
  static Future<void> loadDil(String dilKodu) async {
    if (_currentLanguage == dilKodu && _localizedStrings != null) {
      return;
    }
    try {
      String jsonString = await rootBundle.loadString('assets/dil.json');
      Map<String, dynamic> jsonMap = json.decode(jsonString);

      // 'Veriler' altında istenilen dilin kontrolü yapılır
      if (jsonMap['Veriler'] != null) {
        _localizedStrings = jsonMap['Veriler'];
      } else {
        _localizedStrings = {};
      }
      _currentLanguage = dilKodu;
    } catch (e) {
      print('Dosya bulunamadı veya JSON okuma hatası: $e');
      _localizedStrings = {};
    }
  }

  // Anahtar ile dildeki metni alır
  static String get(String key)  {
    if (_localizedStrings != null && _localizedStrings!.containsKey(key)) {
      return _localizedStrings?[key]?[_currentLanguage] ?? '';
    }
    return '';
  }
}
class DrawerWidget extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Drawer(
      child: ListView(
        padding: EdgeInsets.zero,
        children: <Widget>[
          DrawerHeader(
            decoration: BoxDecoration(),
            child: Text(
              Yazi.get('appbaslik'),
              style: TextStyle(
                color: Colors.white,
                fontSize: 24,
                fontWeight: FontWeight.bold,
                shadows: [
                  Shadow(
                    offset: Offset(2.0, 2.0),
                    blurRadius: 3.0,
                    color: Colors.black.withOpacity(0.5),
                  ),
                ],
              ),
            ),
          ),
          ListTile(
            title: Text(
              Yazi.get('sikayet'),
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            dense: true,
          ),
          Divider(),
          ListTile(
            leading: Icon(Icons.share, color: Color(0xFF5865F2)),
            title: Text(Yazi.get('uygpaylas')),
            onTap: () async {
              await Share.share(Yazi.get('davetpromt'));
            },
          ),
          ListTile(
            leading: Icon(Icons.person, color: Color(0xFF5865F2)),
            title: Text(Yazi.get('yapimcimetin')),
            onTap: () async {
              await EasyLauncher.url(
                  url: 'https://keremkk.can.re', mode: Mode.platformDefault);
            },
          ),
          ListTile(
            leading: FaIcon(Icons.report),
            title: Text(Yazi.get('hatabildir')),
            onTap: () async {
                await EasyLauncher.email(
                    email: "report@keremkk.can.re",
                    subject: "",
                    body: "Merhaba, ");
                     },
          ),
          Divider(),
          ListTile(
            title: Text(
              Yazi.get('yapimci'),
              style: TextStyle(fontWeight: FontWeight.bold),
            ),
            dense: true,
          ),
          SizedBox(height: 20), // Boşluk bırakır
        ],
      ),
    );
  }
}

bool darktema=true;
final List<String> diller = ['Türkçe','English'];
int selectedIndex = 0;
String secilenDil='Türkçe', apiserver = "https://statuesque-marred-clave.glitch.me/";
List<dynamic> users = [];
final random = Random(), dogru = AudioPlayer(), yanlis = AudioPlayer(), yenitur = AudioPlayer();
Future<void> playAudioFromAssetOrUrl(AudioPlayer player, String assetPath, String url) async {
  try {
    if (player.playing) {
      await player.stop();
    }
    await player.setAsset(assetPath);
    await player.play();
  } catch (e) {
    print('Error playing asset: $e');
    try {
      if (player.playing) {
        await player.stop();
      }
      await player.setUrl(url);
      await player.play();
    } catch (urlError) {
      print('Error playing audio from URL: $urlError');
    }
  }
}
Future<void> Dogru() async { await playAudioFromAssetOrUrl(dogru, 'assets/sesler/dogru.mp3', 'https://github.com/keremlolgg/GeoGame/raw/main/assets/sesler/dogru.mp3');}
Future<void> Yanlis() async { await playAudioFromAssetOrUrl(yanlis, 'assets/sesler/yanlis.mp3', 'https://github.com/keremlolgg/GeoGame/raw/main/assets/sesler/yanlis.mp3');}
Future<void> Yenitur() async { await playAudioFromAssetOrUrl(yenitur, 'assets/sesler/yenitur.mp3', 'https://github.com/keremlolgg/GeoGame/raw/main/assets/sesler/yenitur.mp3');}
// Fonksiyonlar
Future<void> readFromFile(Function updateState) async {
  final directory = await getApplicationDocumentsDirectory();
  final filePath = '${directory.path}ayarlar.json';
  final file = File(filePath);

  if (await file.exists()) {
    final contents = await file.readAsString();
    final jsonData = jsonDecode(contents);

    updateState(() {
      darktema = jsonData['darktema'] == true;
      secilenDil = jsonData['secilenDil'];
    });
  } else {
    print('Dosya bulunamadı: ayarlar.json');
    writeToFile();
  }
}
Future<void> writeToFile() async {
  final directory = await getApplicationDocumentsDirectory();
  final filePath = '${directory.path}ayarlar.json';
  final file = File(filePath);
  final data = {
    'darktema': darktema,
    'secilenDil': secilenDil,
  };

  final jsonData = jsonEncode(data);
  await file.writeAsString(jsonData);
}
Future<void> postMessage(String message) async {
  try {
    final targetUrl = '${apiserver}/ekosistem';
    final response = await http.post(
      Uri.parse(targetUrl),
      headers: {'Content-Type': 'application/json'},
      body: json.encode({
        'message': '```'+message+'```',
      }),
    ).timeout(Duration(seconds: 30));

    if (response.statusCode == 200) {
      print('Log başarıyla gönderildi!');
    } else {
      print('Log gönderilemedi: ${response.statusCode}');
    }
  } catch (e) {
    print('Hata: $e');
  }
}
Future<void> postMessage2(String message) async {
  try {
    // Dosya yolunu al
    final directory = await getApplicationDocumentsDirectory();
    final file = File('${directory.path}/log.txt');

    // Mesajı dosyaya yaz
    await file.writeAsString(
      '$message\n',
      mode: FileMode.append, // Dosya zaten varsa üzerine ekler
    );

    print('Log başarıyla dosyaya yazıldı: ${file.path}');
  } catch (e) {
    print('Dosyaya yazılırken hata oluştu: $e');
  }
}
// Listeler
Ulkeler kalici = Ulkeler(
  bayrak: '',
  enisim: '',
  isim: '',
  baskent: '',
  kita: '',
  url: '',
  bilgi: false,
  bm: false,
  enlem: 0.0,
  boylam: 0.0,
  dosyaboyut: 0,
);
List<SalomonBottomBarItem> navBarItems = [
  SalomonBottomBarItem(
    icon: const Icon(Icons.home),
    selectedColor: Colors.purple,
    title: const Text(''),
  ),
  SalomonBottomBarItem(
    icon: const Icon(FontAwesomeIcons.info),
    selectedColor: Colors.teal,
    title: const Text(''),
  ),
  SalomonBottomBarItem(
    icon: const Icon(Icons.settings),
    selectedColor: Colors.orange,
    title: const Text(''),
  ),
];
List<Ulkeler> ulke = [
  Ulkeler(
      bayrak: "assets/bayraklar/moldova.png",
      enisim: "Moldova",
      isim: "Moldova",
      baskent: "Kişinev",
      kita: "Europe",
      url: "https://flagcdn.com/w320/md.png",
      bilgi: false,
      bm: true,
      enlem: 47,
      boylam: 29,
      dosyaboyut: 2600
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/amerikabirlesikdevletleri.png",
      enisim: "Unitedstates",
      isim: "Amerikabirlesikdevletleri",
      baskent: "Washington, DC",
      kita: "Americas",
      url: "https://flagcdn.com/w320/us.png",
      bilgi: false,
      bm: true,
      enlem: 38,
      boylam: -97,
      dosyaboyut: 1289
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mayotte.png",
      enisim: "Mayotte",
      isim: "Mayotte",
      baskent: "Mamutzu",
      kita: "Africa",
      url: "https://flagcdn.com/w320/yt.png",
      bilgi: false,
      bm: false,
      enlem: -12.83,
      boylam: 45.17,
      dosyaboyut: 8185
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/nauru.png",
      enisim: "Nauru",
      isim: "Nauru",
      baskent: "Yaren",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/nr.png",
      bilgi: false,
      bm: true,
      enlem: -0.53,
      boylam: 166.92,
      dosyaboyut: 651
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mozambik.png",
      enisim: "Mozambique",
      isim: "Mozambik",
      baskent: "Maputo",
      kita: "Africa",
      url: "https://flagcdn.com/w320/mz.png",
      bilgi: false,
      bm: true,
      enlem: -18.25,
      boylam: 35,
      dosyaboyut: 2298
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/brezilya.png",
      enisim: "Brazil",
      isim: "Brezilya",
      baskent: "Brazilya",
      kita: "Americas",
      url: "https://flagcdn.com/w320/br.png",
      bilgi: false,
      bm: true,
      enlem: -10,
      boylam: -55,
      dosyaboyut: 2883
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/yesilburun.png",
      enisim: "Capeverde",
      isim: "Yesilburun",
      baskent: "Praya",
      kita: "Africa",
      url: "https://flagcdn.com/w320/cv.png",
      bilgi: false,
      bm: true,
      enlem: 16.54,
      boylam: -23.04,
      dosyaboyut: 909
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ekvatorginesi.png",
      enisim: "Equatorialguinea",
      isim: "Ekvatorginesi",
      baskent: "Malabo",
      kita: "Africa",
      url: "https://flagcdn.com/w320/gq.png",
      bilgi: false,
      bm: true,
      enlem: 2,
      boylam: 10,
      dosyaboyut: 1923
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/arnavutluk.png",
      enisim: "Albania",
      isim: "Arnavutluk",
      baskent: "Tiran",
      kita: "Europe",
      url: "https://flagcdn.com/w320/al.png",
      bilgi: false,
      bm: true,
      enlem: 41,
      boylam: 20,
      dosyaboyut: 3044
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/abdvirjinadalari.png",
      enisim: "Unitedstatesvirginislands",
      isim: "Abdvirjinadalari",
      baskent: "Charlotte Amalie",
      kita: "Americas",
      url: "https://flagcdn.com/w320/vi.png",
      bilgi: false,
      bm: false,
      enlem: 18.35,
      boylam: -64.93,
      dosyaboyut: 9362
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/niue.png",
      enisim: "Niue",
      isim: "Niue",
      baskent: "Alofi",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/nu.png",
      bilgi: false,
      bm: false,
      enlem: -19.03,
      boylam: -169.87,
      dosyaboyut: 1457
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/palau.png",
      enisim: "Palau",
      isim: "Palau",
      baskent: "Ngerulmud",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/pw.png",
      bilgi: false,
      bm: true,
      enlem: 7.5,
      boylam: 134.5,
      dosyaboyut: 738
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/nijerya.png",
      enisim: "Nigeria",
      isim: "Nijerya",
      baskent: "Abuja",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ng.png",
      bilgi: false,
      bm: true,
      enlem: 10,
      boylam: 8,
      dosyaboyut: 157
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/virjinadalari.png",
      enisim: "Britishvirginislands",
      isim: "Virjinadalari",
      baskent: "Road town",
      kita: "Americas",
      url: "https://flagcdn.com/w320/vg.png",
      bilgi: false,
      bm: false,
      enlem: 18.43,
      boylam: -64.62,
      dosyaboyut: 4437
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gambiya.png",
      enisim: "Gambia",
      isim: "Gambiya",
      baskent: "Banjul",
      kita: "Africa",
      url: "https://flagcdn.com/w320/gm.png",
      bilgi: false,
      bm: true,
      enlem: 13.47,
      boylam: -16.57,
      dosyaboyut: 248
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/somali.png",
      enisim: "Somalia",
      isim: "Somali",
      baskent: "Mogadişu",
      kita: "Africa",
      url: "https://flagcdn.com/w320/so.png",
      bilgi: false,
      bm: true,
      enlem: 10,
      boylam: 49,
      dosyaboyut: 693
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/yemen.png",
      enisim: "Yemen",
      isim: "Yemen",
      baskent: "Sanaa",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ye.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: 48,
      dosyaboyut: 153
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/malezya.png",
      enisim: "Malaysia",
      isim: "Malezya",
      baskent: "Kualalumpur",
      kita: "Asia",
      url: "https://flagcdn.com/w320/my.png",
      bilgi: false,
      bm: true,
      enlem: 2.5,
      boylam: 112.5,
      dosyaboyut: 1139
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/dominika.png",
      enisim: "Dominica",
      isim: "Dominika",
      baskent: "Roseau",
      kita: "Americas",
      url: "https://flagcdn.com/w320/dm.png",
      bilgi: false,
      bm: true,
      enlem: 15.42,
      boylam: -61.33,
      dosyaboyut: 1715
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/birlesikkrallik.png",
      enisim: "Unitedkingdom",
      isim: "Birlesikkrallik",
      baskent: "Londra",
      kita: "Europe",
      url: "https://flagcdn.com/w320/gb.png",
      bilgi: false,
      bm: true,
      enlem: 54,
      boylam: -2,
      dosyaboyut: 980
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/madagaskar.png",
      enisim: "Madagascar",
      isim: "Madagaskar",
      baskent: "Antananarivo",
      kita: "Africa",
      url: "https://flagcdn.com/w320/mg.png",
      bilgi: false,
      bm: true,
      enlem: -20,
      boylam: 47,
      dosyaboyut: 266
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sahrademokratikarapcumhuriyeti.png",
      enisim: "Westernsahara",
      isim: "Sahrademokratikarapcumhuriyeti",
      baskent: "Layun",
      kita: "Africa",
      url: "https://flagcdn.com/w320/eh.png",
      bilgi: false,
      bm: false,
      enlem: 24.5,
      boylam: -13,
      dosyaboyut: 1083
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kibris.png",
      enisim: "Cyprus",
      isim: "Kibris",
      baskent: "Lefkoşa",
      kita: "Europe",
      url: "https://flagcdn.com/w320/cy.png",
      bilgi: false,
      bm: true,
      enlem: 35,
      boylam: 33,
      dosyaboyut: 2172
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/antiguavebarbuda.png",
      enisim: "Antiguaandbarbuda",
      isim: "Antiguavebarbuda",
      baskent: "St. John's",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ag.png",
      bilgi: false,
      bm: true,
      enlem: 17.05,
      boylam: -61.8,
      dosyaboyut: 2325
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/irlanda.png",
      enisim: "Ireland",
      isim: "Irlanda",
      baskent: "Dublin",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ie.png",
      bilgi: false,
      bm: true,
      enlem: 53,
      boylam: -8,
      dosyaboyut: 219
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/paraguay.png",
      enisim: "Paraguay",
      isim: "Paraguay",
      baskent: "Asunsion",
      kita: "Americas",
      url: "https://flagcdn.com/w320/py.png",
      bilgi: false,
      bm: true,
      enlem: -23,
      boylam: -58,
      dosyaboyut: 1190
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/srilanka.png",
      enisim: "Srilanka",
      isim: "Srilanka",
      baskent: "Kolombo ve Sri Jayawardenapura-Kotte",
      kita: "Asia",
      url: "https://flagcdn.com/w320/lk.png",
      bilgi: false,
      bm: true,
      enlem: 7,
      boylam: 81,
      dosyaboyut: 3493
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guneyafrika.png",
      enisim: "Southafrica",
      isim: "Guneyafrika",
      baskent: "Cape Town, Pretorya ve Bloemfontein",
      kita: "Africa",
      url: "https://flagcdn.com/w320/za.png",
      bilgi: false,
      bm: true,
      enlem: -29,
      boylam: 24,
      dosyaboyut: 985
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kuveyt.png",
      enisim: "Kuwait",
      isim: "Kuveyt",
      baskent: "Kuveyt",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kw.png",
      bilgi: false,
      bm: true,
      enlem: 29.5,
      boylam: 45.75,
      dosyaboyut: 527
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cezayir.png",
      enisim: "Algeria",
      isim: "Cezayir",
      baskent: "Cezayir",
      kita: "Africa",
      url: "https://flagcdn.com/w320/dz.png",
      bilgi: false,
      bm: true,
      enlem: 28,
      boylam: 3,
      dosyaboyut: 989
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/hirvatistan.png",
      enisim: "Croatia",
      isim: "Hirvatistan",
      baskent: "Zagreb",
      kita: "Europe",
      url: "https://flagcdn.com/w320/hr.png",
      bilgi: false,
      bm: true,
      enlem: 45.17,
      boylam: 15.5,
      dosyaboyut: 1810
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/martinik.png",
      enisim: "Martinique",
      isim: "Martinik",
      baskent: "Fort-de-France",
      kita: "Americas",
      url: "https://flagcdn.com/w320/mq.png",
      bilgi: false,
      bm: false,
      enlem: 14.67,
      boylam: -61,
      dosyaboyut: 957
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sierraleone.png",
      enisim: "Sierraleone",
      isim: "Sierraleone",
      baskent: "Freetown",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sl.png",
      bilgi: false,
      bm: true,
      enlem: 8.5,
      boylam: -11.5,
      dosyaboyut: 153
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kuzeymarianaadalari.png",
      enisim: "Northernmarianaislands",
      isim: "Kuzeymarianaadalari",
      baskent: "Saipan",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/mp.png",
      bilgi: false,
      bm: false,
      enlem: 15.2,
      boylam: 145.75,
      dosyaboyut: 9029
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ruanda.png",
      enisim: "Rwanda",
      isim: "Ruanda",
      baskent: "Kigali",
      kita: "Africa",
      url: "https://flagcdn.com/w320/rw.png",
      bilgi: false,
      bm: true,
      enlem: -2,
      boylam: 30,
      dosyaboyut: 1180
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/suriye.png",
      enisim: "Syria",
      isim: "Suriye",
      baskent: "Şam",
      kita: "Asia",
      url: "https://flagcdn.com/w320/sy.png",
      bilgi: false,
      bm: true,
      enlem: 35,
      boylam: 38,
      dosyaboyut: 819
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintvincentvegrenadinler.png",
      enisim: "Saintvincentandthegrenadines",
      isim: "Saintvincentvegrenadinler",
      baskent: "Kingstown",
      kita: "Americas",
      url: "https://flagcdn.com/w320/vc.png",
      bilgi: false,
      bm: true,
      enlem: 13.25,
      boylam: -61.2,
      dosyaboyut: 1087
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kosova.png",
      enisim: "Kosovo",
      isim: "Kosova",
      baskent: "Priştine",
      kita: "Europe",
      url: "https://flagcdn.com/w320/xk.png",
      bilgi: false,
      bm: false,
      enlem: 42.67,
      boylam: 21.17,
      dosyaboyut: 1730
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintlucia.png",
      enisim: "Saintlucia",
      isim: "Saintlucia",
      baskent: "Castries",
      kita: "Americas",
      url: "https://flagcdn.com/w320/lc.png",
      bilgi: false,
      bm: true,
      enlem: 13.88,
      boylam: -60.97,
      dosyaboyut: 1552
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/honduras.png",
      enisim: "Honduras",
      isim: "Honduras",
      baskent: "Tegucigalpa",
      kita: "Americas",
      url: "https://flagcdn.com/w320/hn.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: -86.5,
      dosyaboyut: 595
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/urdun.png",
      enisim: "Jordan",
      isim: "Urdun",
      baskent: "Amman",
      kita: "Asia",
      url: "https://flagcdn.com/w320/jo.png",
      bilgi: false,
      bm: true,
      enlem: 31,
      boylam: 36,
      dosyaboyut: 658
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tuvalu.png",
      enisim: "Tuvalu",
      isim: "Tuvalu",
      baskent: "Funafuti",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/tv.png",
      bilgi: false,
      bm: true,
      enlem: -8,
      boylam: 178,
      dosyaboyut: 1820
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/nepal.png",
      enisim: "Nepal",
      isim: "Nepal",
      baskent: "Kathmandu",
      kita: "Asia",
      url: "https://flagcdn.com/w320/np.png",
      bilgi: false,
      bm: true,
      enlem: 28,
      boylam: 84,
      dosyaboyut: 3611
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/liberya.png",
      enisim: "Liberia",
      isim: "Liberya",
      baskent: "Monrovia",
      kita: "Africa",
      url: "https://flagcdn.com/w320/lr.png",
      bilgi: false,
      bm: true,
      enlem: 6.5,
      boylam: -9.5,
      dosyaboyut: 606
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/avusturya.png",
      enisim: "Austria",
      isim: "Avusturya",
      baskent: "Viyana",
      kita: "Europe",
      url: "https://flagcdn.com/w320/at.png",
      bilgi: false,
      bm: true,
      enlem: 47.33,
      boylam: 13.33,
      dosyaboyut: 118
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guernsey.png",
      enisim: "Guernsey",
      isim: "Guernsey",
      baskent: "Saint Peter Port",
      kita: "Europe",
      url: "https://flagcdn.com/w320/gg.png",
      bilgi: false,
      bm: false,
      enlem: 49.47,
      boylam: -2.58,
      dosyaboyut: 570
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ortaafrikacumhuriyeti.png",
      enisim: "Centralafricanrepublic",
      isim: "Ortaafrikacumhuriyeti",
      baskent: "Bangui",
      kita: "Africa",
      url: "https://flagcdn.com/w320/cf.png",
      bilgi: false,
      bm: true,
      enlem: 7,
      boylam: 21,
      dosyaboyut: 622
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/moritanya.png",
      enisim: "Mauritania",
      isim: "Moritanya",
      baskent: "Nuakşot",
      kita: "Africa",
      url: "https://flagcdn.com/w320/mr.png",
      bilgi: false,
      bm: true,
      enlem: 20,
      boylam: -12,
      dosyaboyut: 1002
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cibuti.png",
      enisim: "Djibouti",
      isim: "Cibuti",
      baskent: "Cibuti",
      kita: "Africa",
      url: "https://flagcdn.com/w320/dj.png",
      bilgi: false,
      bm: true,
      enlem: 11.5,
      boylam: 43,
      dosyaboyut: 1474
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fiji.png",
      enisim: "Fiji",
      isim: "Fiji",
      baskent: "Suva",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/fj.png",
      bilgi: false,
      bm: true,
      enlem: 17.71,
      boylam: 178.06,
      dosyaboyut: 3250
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/norvec.png",
      enisim: "Norway",
      isim: "Norvec",
      baskent: "Oslo",
      kita: "Europe",
      url: "https://flagcdn.com/w320/no.png",
      bilgi: false,
      bm: true,
      enlem: 62,
      boylam: 10,
      dosyaboyut: 323
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/letonya.png",
      enisim: "Latvia",
      isim: "Letonya",
      baskent: "Riga",
      kita: "Europe",
      url: "https://flagcdn.com/w320/lv.png",
      bilgi: false,
      bm: true,
      enlem: 57,
      boylam: 25,
      dosyaboyut: 112
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/falklandmalvinaadalari.png",
      enisim: "Falklandislands",
      isim: "Falklandmalvinaadalari",
      baskent: "Stanley",
      kita: "Americas",
      url: "https://flagcdn.com/w320/fk.png",
      bilgi: false,
      bm: false,
      enlem: -51.75,
      boylam: -59,
      dosyaboyut: 5318
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kazakistan.png",
      enisim: "Kazakhstan",
      isim: "Kazakistan",
      baskent: "Nursultan",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kz.png",
      bilgi: false,
      bm: true,
      enlem: 48.02,
      boylam: 66.92,
      dosyaboyut: 2960
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/aland.png",
      enisim: "Alandislands",
      isim: "Aland",
      baskent: "Mariehamn",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ax.png",
      bilgi: false,
      bm: false,
      enlem: 60.12,
      boylam: 19.9,
      dosyaboyut: 311
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/turkmenistan.png",
      enisim: "Turkmenistan",
      isim: "Turkmenistan",
      baskent: "Aşkabat",
      kita: "Asia",
      url: "https://flagcdn.com/w320/tm.png",
      bilgi: false,
      bm: true,
      enlem: 40,
      boylam: 60,
      dosyaboyut: 7750
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cocoskeelingadalari.png",
      enisim: "Cocoskeelingislands",
      isim: "Cocoskeelingadalari",
      baskent: "Westisland",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/cc.png",
      bilgi: false,
      bm: false,
      enlem: 12.16,
      boylam: 96.87,
      dosyaboyut: 1989
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bulgaristan.png",
      enisim: "Bulgaria",
      isim: "Bulgaristan",
      baskent: "Sofya",
      kita: "Europe",
      url: "https://flagcdn.com/w320/bg.png",
      bilgi: false,
      bm: true,
      enlem: 43,
      boylam: 25,
      dosyaboyut: 151
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tokelau.png",
      enisim: "Tokelau",
      isim: "Tokelau",
      baskent: "Fakaofo, Atafu ve Nukunonu",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/tk.png",
      bilgi: false,
      bm: false,
      enlem: -9,
      boylam: -172,
      dosyaboyut: 1418
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/yenikaledonya.png",
      enisim: "Newcaledonia",
      isim: "Yenikaledonya",
      baskent: "Nouméa",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/nc.png",
      bilgi: false,
      bm: false,
      enlem: -21.5,
      boylam: 165.5,
      dosyaboyut: 1715
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/barbados.png",
      enisim: "Barbados",
      isim: "Barbados",
      baskent: "Bridgetown",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bb.png",
      bilgi: false,
      bm: true,
      enlem: 13.17,
      boylam: -59.53,
      dosyaboyut: 998
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saotomeandprincipe.png",
      enisim: "Saotomeandprincipe",
      isim: "Saotomeandprincipe",
      baskent: "Sao Tome",
      kita: "Africa",
      url: "https://flagcdn.com/w320/st.png",
      bilgi: false,
      bm: true,
      enlem: 1,
      boylam: 7,
      dosyaboyut: 1077
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/antarktika.png",
      enisim: "Antarctica",
      isim: "Antarktika",
      baskent: "Antartika",
      kita: "Antarctic",
      url: "https://flagcdn.com/w320/aq.png",
      bilgi: false,
      bm: false,
      enlem: -90,
      boylam: 0,
      dosyaboyut: 1354
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/brunei.png",
      enisim: "Brunei",
      isim: "Brunei",
      baskent: "Bandar Seri Begavan",
      kita: "Asia",
      url: "https://flagcdn.com/w320/bn.png",
      bilgi: false,
      bm: true,
      enlem: 4.5,
      boylam: 114.67,
      dosyaboyut: 3402
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/butan.png",
      enisim: "Bhutan",
      isim: "Butan",
      baskent: "Thimphu",
      kita: "Asia",
      url: "https://flagcdn.com/w320/bt.png",
      bilgi: false,
      bm: true,
      enlem: 27.5,
      boylam: 90.5,
      dosyaboyut: 8230
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kamerun.png",
      enisim: "Cameroon",
      isim: "Kamerun",
      baskent: "Yaunde",
      kita: "Africa",
      url: "https://flagcdn.com/w320/cm.png",
      bilgi: false,
      bm: true,
      enlem: 6,
      boylam: 12,
      dosyaboyut: 637
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/arjantin.png",
      enisim: "Argentina",
      isim: "Arjantin",
      baskent: "Buenos Aires",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ar.png",
      bilgi: false,
      bm: true,
      enlem: -34,
      boylam: -64,
      dosyaboyut: 1578
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/azerbaycan.png",
      enisim: "Azerbaijan",
      isim: "Azerbaycan",
      baskent: "Bakü",
      kita: "Asia",
      url: "https://flagcdn.com/w320/az.png",
      bilgi: false,
      bm: true,
      enlem: 40.5,
      boylam: 47.5,
      dosyaboyut: 706
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/meksika.png",
      enisim: "Mexico",
      isim: "Meksika",
      baskent: "Meksiko",
      kita: "Americas",
      url: "https://flagcdn.com/w320/mx.png",
      bilgi: false,
      bm: true,
      enlem: 23,
      boylam: -102,
      dosyaboyut: 3655
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fas.png",
      enisim: "Morocco",
      isim: "Fas",
      baskent: "Rabat",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ma.png",
      bilgi: false,
      bm: true,
      enlem: 32,
      boylam: -5,
      dosyaboyut: 928
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guatemala.png",
      enisim: "Guatemala",
      isim: "Guatemala",
      baskent: "Guatemalacity",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gt.png",
      bilgi: false,
      bm: true,
      enlem: 15.5,
      boylam: -90.25,
      dosyaboyut: 2518
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kenya.png",
      enisim: "Kenya",
      isim: "Kenya",
      baskent: "Nairobi",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ke.png",
      bilgi: false,
      bm: true,
      enlem: 1,
      boylam: 38,
      dosyaboyut: 1966
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/malta.png",
      enisim: "Malta",
      isim: "Malta",
      baskent: "Valetta",
      kita: "Europe",
      url: "https://flagcdn.com/w320/mt.png",
      bilgi: false,
      bm: true,
      enlem: 35.94,
      boylam: 14.38,
      dosyaboyut: 1073
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cekya.png",
      enisim: "Czechia",
      isim: "Cekya",
      baskent: "Prag",
      kita: "Europe",
      url: "https://flagcdn.com/w320/cz.png",
      bilgi: false,
      bm: true,
      enlem: 49.75,
      boylam: 15.5,
      dosyaboyut: 940
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cebelitarik.png",
      enisim: "Gibraltar",
      isim: "Cebelitarik",
      baskent: "Cebelitarık",
      kita: "Europe",
      url: "https://flagcdn.com/w320/gi.png",
      bilgi: false,
      bm: false,
      enlem: 36.13,
      boylam: -5.35,
      dosyaboyut: 2033
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/aruba.png",
      enisim: "Aruba",
      isim: "Aruba",
      baskent: "Oranjestad",
      kita: "Americas",
      url: "https://flagcdn.com/w320/aw.png",
      bilgi: false,
      bm: false,
      enlem: 12.5,
      boylam: -69.97,
      dosyaboyut: 735
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintbarthelemy.png",
      enisim: "Saintbarthelemy",
      isim: "Saintbarthelemy",
      baskent: "Gustavia",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bl.png",
      bilgi: false,
      bm: false,
      enlem: 18.5,
      boylam: -63.42,
      dosyaboyut: 11667
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/monako.png",
      enisim: "Monaco",
      isim: "Monako",
      baskent: "Monako",
      kita: "Europe",
      url: "https://flagcdn.com/w320/mc.png",
      bilgi: false,
      bm: true,
      enlem: 43.73,
      boylam: 7.4,
      dosyaboyut: 124
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/birlesikarapemirlikleri.png",
      enisim: "Unitedarabemirates",
      isim: "Birlesikarapemirlikleri",
      baskent: "Abu Dabi",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ae.png",
      bilgi: false,
      bm: true,
      enlem: 24,
      boylam: 54,
      dosyaboyut: 233
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guneysudan.png",
      enisim: "Southsudan",
      isim: "Guneysudan",
      baskent: "Juba",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ss.png",
      bilgi: false,
      bm: true,
      enlem: 7,
      boylam: 30,
      dosyaboyut: 1000
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/portoriko.png",
      enisim: "Puertorico",
      isim: "Portoriko",
      baskent: "San juan",
      kita: "Americas",
      url: "https://flagcdn.com/w320/pr.png",
      bilgi: false,
      bm: false,
      enlem: 18.25,
      boylam: -66.5,
      dosyaboyut: 1474
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/elsalvador.png",
      enisim: "Elsalvador",
      isim: "Elsalvador",
      baskent: "San salvador",
      kita: "Americas",
      url: "https://flagcdn.com/w320/sv.png",
      bilgi: false,
      bm: true,
      enlem: 13.83,
      boylam: -88.92,
      dosyaboyut: 2363
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fransa.png",
      enisim: "France",
      isim: "Fransa",
      baskent: "Paris",
      kita: "Europe",
      url: "https://flagcdn.com/w320/fr.png",
      bilgi: false,
      bm: true,
      enlem: 46,
      boylam: 2,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/nijer.png",
      enisim: "Niger",
      isim: "Nijer",
      baskent: "Niamey",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ne.png",
      bilgi: false,
      bm: true,
      enlem: 16,
      boylam: 8,
      dosyaboyut: 645
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fildisisahili.png",
      enisim: "Ivorycoast",
      isim: "Fildisisahili",
      baskent: "Yamoussoukro",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ci.png",
      bilgi: false,
      bm: true,
      enlem: 8,
      boylam: -5,
      dosyaboyut: 252
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guneygeorgiaveguneysandwichadalari.png",
      enisim: "Southgeorgia",
      isim: "Guneygeorgiaveguneysandwichadalari",
      baskent: "Kingedwardpoint",
      kita: "Antarctic",
      url: "https://flagcdn.com/w320/gs.png",
      bilgi: false,
      bm: false,
      enlem: -54.5,
      boylam: -37,
      dosyaboyut: 6026
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/botsvana.png",
      enisim: "Botswana",
      isim: "Botsvana",
      baskent: "Gaborone",
      kita: "Africa",
      url: "https://flagcdn.com/w320/bw.png",
      bilgi: false,
      bm: true,
      enlem: -22,
      boylam: 24,
      dosyaboyut: 199
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/britanyahintokyanusutopraklari.png",
      enisim: "Britishindianoceanterritory",
      isim: "Britanyahintokyanusutopraklari",
      baskent: "Diegogarcia",
      kita: "Africa",
      url: "https://flagcdn.com/w320/io.png",
      bilgi: false,
      bm: false,
      enlem: -6,
      boylam: 71.5,
      dosyaboyut: 7213
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ozbekistan.png",
      enisim: "Uzbekistan",
      isim: "Ozbekistan",
      baskent: "Taşkent",
      kita: "Asia",
      url: "https://flagcdn.com/w320/uz.png",
      bilgi: false,
      bm: true,
      enlem: 41,
      boylam: 64,
      dosyaboyut: 760
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tunus.png",
      enisim: "Tunisia",
      isim: "Tunus",
      baskent: "Tunis",
      kita: "Africa",
      url: "https://flagcdn.com/w320/tn.png",
      bilgi: false,
      bm: true,
      enlem: 34,
      boylam: 9,
      dosyaboyut: 1128
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/hongkong.png",
      enisim: "Hongkong",
      isim: "Hongkong",
      baskent: "Victoria",
      kita: "Asia",
      url: "https://flagcdn.com/w320/hk.png",
      bilgi: false,
      bm: false,
      enlem: 22.27,
      boylam: 114.19,
      dosyaboyut: 2045
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kuzeymakedonya.png",
      enisim: "Northmacedonia",
      isim: "Kuzeymakedonya",
      baskent: "Üsküp",
      kita: "Europe",
      url: "https://flagcdn.com/w320/mk.png",
      bilgi: false,
      bm: true,
      enlem: 41.83,
      boylam: 22,
      dosyaboyut: 1613
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/surinam.png",
      enisim: "Suriname",
      isim: "Surinam",
      baskent: "Paramaribo",
      kita: "Americas",
      url: "https://flagcdn.com/w320/sr.png",
      bilgi: false,
      bm: true,
      enlem: 4,
      boylam: -56,
      dosyaboyut: 686
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/belcika.png",
      enisim: "Belgium",
      isim: "Belcika",
      baskent: "Brüksel",
      kita: "Europe",
      url: "https://flagcdn.com/w320/be.png",
      bilgi: false,
      bm: true,
      enlem: 50.83,
      boylam: 4,
      dosyaboyut: 292
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/amerikansamoasi.png",
      enisim: "Americansamoa",
      isim: "Amerikansamoasi",
      baskent: "Pago Pago",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/as.png",
      bilgi: false,
      bm: false,
      enlem: -14.33,
      boylam: -170,
      dosyaboyut: 3763
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/solomonadalari.png",
      enisim: "Solomonislands",
      isim: "Solomonadalari",
      baskent: "Honiara",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/sb.png",
      bilgi: false,
      bm: true,
      enlem: -8,
      boylam: 159,
      dosyaboyut: 1446
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ukrayna.png",
      enisim: "Ukraine",
      isim: "Ukrayna",
      baskent: "Kiev",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ua.png",
      bilgi: false,
      bm: true,
      enlem: 49,
      boylam: 32,
      dosyaboyut: 146
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/finlandiya.png",
      enisim: "Finland",
      isim: "Finlandiya",
      baskent: "Helsinki",
      kita: "Europe",
      url: "https://flagcdn.com/w320/fi.png",
      bilgi: false,
      bm: true,
      enlem: 64,
      boylam: 26,
      dosyaboyut: 240
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/burkinafaso.png",
      enisim: "Burkinafaso",
      isim: "Burkinafaso",
      baskent: "Ouagadougou",
      kita: "Africa",
      url: "https://flagcdn.com/w320/bf.png",
      bilgi: false,
      bm: true,
      enlem: 13,
      boylam: -2,
      dosyaboyut: 702
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bosnahersek.png",
      enisim: "Bosniaandherzegovina",
      isim: "Bosnahersek",
      baskent: "Saraybosna",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ba.png",
      bilgi: false,
      bm: true,
      enlem: 44,
      boylam: 18,
      dosyaboyut: 1197
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/iran.png",
      enisim: "Iran",
      isim: "Iran",
      baskent: "Tahran",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ir.png",
      bilgi: false,
      bm: true,
      enlem: 32,
      boylam: 53,
      dosyaboyut: 2156
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kuba.png",
      enisim: "Cuba",
      isim: "Kuba",
      baskent: "Havana",
      kita: "Americas",
      url: "https://flagcdn.com/w320/cu.png",
      bilgi: false,
      bm: true,
      enlem: 21.5,
      boylam: -80,
      dosyaboyut: 1059
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/eritre.png",
      enisim: "Eritrea",
      isim: "Eritre",
      baskent: "Asmara",
      kita: "Africa",
      url: "https://flagcdn.com/w320/er.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: 39,
      dosyaboyut: 2447
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/slovakya.png",
      enisim: "Slovakia",
      isim: "Slovakya",
      baskent: "Bratislava",
      kita: "Europe",
      url: "https://flagcdn.com/w320/sk.png",
      bilgi: false,
      bm: true,
      enlem: 48.67,
      boylam: 19.5,
      dosyaboyut: 1366
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/litvanya.png",
      enisim: "Lithuania",
      isim: "Litvanya",
      baskent: "Vilnius",
      kita: "Europe",
      url: "https://flagcdn.com/w320/lt.png",
      bilgi: false,
      bm: true,
      enlem: 56,
      boylam: 24,
      dosyaboyut: 151
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintmartin.png",
      enisim: "Saintmartin",
      isim: "Saintmartin",
      baskent: "Marigot",
      kita: "Americas",
      url: "https://flagcdn.com/w320/mf.png",
      bilgi: false,
      bm: false,
      enlem: 18.07,
      boylam: 63.05,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/pitcairnadalari.png",
      enisim: "Pitcairnislands",
      isim: "Pitcairnadalari",
      baskent: "Adamstown",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/pn.png",
      bilgi: false,
      bm: false,
      enlem: -25.07,
      boylam: -130.1,
      dosyaboyut: 4822
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ginebissau.png",
      enisim: "Guineabissau",
      isim: "Ginebissau",
      baskent: "Bissau",
      kita: "Africa",
      url: "https://flagcdn.com/w320/gw.png",
      bilgi: false,
      bm: false,
      enlem: 12,
      boylam: -15,
      dosyaboyut: 519
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/montserrat.png",
      enisim: "Montserrat",
      isim: "Montserrat",
      baskent: "Plymouth",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ms.png",
      bilgi: false,
      bm: false,
      enlem: 16.75,
      boylam: -62.2,
      dosyaboyut: 2440
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/turkiye.png",
      enisim: "Turkey",
      isim: "Turkiye",
      baskent: "Ankara",
      kita: "Asia",
      url: "https://flagcdn.com/w320/tr.png",
      bilgi: false,
      bm: true,
      enlem: 39,
      boylam: 35,
      dosyaboyut: 947
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/filipinler.png",
      enisim: "Philippines",
      isim: "Filipinler",
      baskent: "Manila",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ph.png",
      bilgi: false,
      bm: true,
      enlem: 13,
      boylam: 122,
      dosyaboyut: 1665
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/vanuatu.png",
      enisim: "Vanuatu",
      isim: "Vanuatu",
      baskent: "Port villa",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/vu.png",
      bilgi: false,
      bm: true,
      enlem: -16,
      boylam: 167,
      dosyaboyut: 1682
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bolivya.png",
      enisim: "Bolivia",
      isim: "Bolivya",
      baskent: "Sucre",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bo.png",
      bilgi: false,
      bm: true,
      enlem: -17,
      boylam: -65,
      dosyaboyut: 3978
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintkittsvenevis.png",
      enisim: "Saintkittsandnevis",
      isim: "Saintkittsvenevis",
      baskent: "Basseterre",
      kita: "Americas",
      url: "https://flagcdn.com/w320/kn.png",
      bilgi: false,
      bm: true,
      enlem: 17.33,
      boylam: -62.75,
      dosyaboyut: 2098
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/romanya.png",
      enisim: "Romania",
      isim: "Romanya",
      baskent: "Bükreş",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ro.png",
      bilgi: false,
      bm: true,
      enlem: 46,
      boylam: 25,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kambocya.png",
      enisim: "Cambodia",
      isim: "Kambocya",
      baskent: "Phnompenh",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kh.png",
      bilgi: false,
      bm: true,
      enlem: 13,
      boylam: 105,
      dosyaboyut: 2613
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/zimbabve.png",
      enisim: "Zimbabwe",
      isim: "Zimbabve",
      baskent: "Harare",
      kita: "Africa",
      url: "https://flagcdn.com/w320/zw.png",
      bilgi: false,
      bm: true,
      enlem: -20,
      boylam: 30,
      dosyaboyut: 1548
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/jersey.png",
      enisim: "Jersey",
      isim: "Jersey",
      baskent: "Sainthelier",
      kita: "Europe",
      url: "https://flagcdn.com/w320/je.png",
      bilgi: false,
      bm: false,
      enlem: 49.25,
      boylam: -2.17,
      dosyaboyut: 2978
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kirgizistan.png",
      enisim: "Kyrgyzstan",
      isim: "Kirgizistan",
      baskent: "Bishkek",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kg.png",
      bilgi: false,
      bm: true,
      enlem: 41,
      boylam: 75,
      dosyaboyut: 3399
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/karayiphollandasi.png",
      enisim: "Caribbeannetherlands",
      isim: "Karayiphollandasi",
      baskent: "Kralendijk",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bq.png",
      bilgi: false,
      bm: false,
      enlem: 12.18,
      boylam: -68.25,
      dosyaboyut: 2386
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guyana.png",
      enisim: "Guyana",
      isim: "Guyana",
      baskent: "Georgetown",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gy.png",
      bilgi: false,
      bm: true,
      enlem: 5,
      boylam: -59,
      dosyaboyut: 1438
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/amerikabirlesikdevletlerikucukdisadalari.png",
      enisim: "Unitedstatesminoroutlyingislands",
      isim: "Amerikabirlesikdevletlerikucukdisadalari",
      baskent: "Washingtondc",
      kita: "Americas",
      url: "https://flagcdn.com/w320/um.png",
      bilgi: false,
      bm: false,
      enlem: 19.3,
      boylam: 166.63,
      dosyaboyut: 1289
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ermenistan.png",
      enisim: "Armenia",
      isim: "Ermenistan",
      baskent: "Yerevan",
      kita: "Asia",
      url: "https://flagcdn.com/w320/am.png",
      bilgi: false,
      bm: true,
      enlem: 40,
      boylam: 45,
      dosyaboyut: 198
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/lubnan.png",
      enisim: "Lebanon",
      isim: "Lubnan",
      baskent: "Beirut",
      kita: "Asia",
      url: "https://flagcdn.com/w320/lb.png",
      bilgi: false,
      bm: true,
      enlem: 33.83,
      boylam: 35.83,
      dosyaboyut: 1239
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/karadag.png",
      enisim: "Montenegro",
      isim: "Karadag",
      baskent: "Podgorica",
      kita: "Europe",
      url: "https://flagcdn.com/w320/me.png",
      bilgi: false,
      bm: true,
      enlem: 42.5,
      boylam: 19.3,
      dosyaboyut: 3568
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gronland.png",
      enisim: "Greenland",
      isim: "Gronland",
      baskent: "Nuuk",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gl.png",
      bilgi: false,
      bm: false,
      enlem: 72,
      boylam: -40,
      dosyaboyut: 1104
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/papuayenigine.png",
      enisim: "Papuanewguinea",
      isim: "Papuayenigine",
      baskent: "Port moresby",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/pg.png",
      bilgi: false,
      bm: true,
      enlem: -6,
      boylam: 147,
      dosyaboyut: 2772
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/zambiya.png",
      enisim: "Zambia",
      isim: "Zambiya",
      baskent: "Lusaka",
      kita: "Africa",
      url: "https://flagcdn.com/w320/zm.png",
      bilgi: false,
      bm: true,
      enlem: -15,
      boylam: 30,
      dosyaboyut: 1062
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/trinidadvetobago.png",
      enisim: "Trinidadandtobago",
      isim: "Trinidadvetobago",
      baskent: "Port Of Spain",
      kita: "Americas",
      url: "https://flagcdn.com/w320/tt.png",
      bilgi: false,
      bm: true,
      enlem: 10.69,
      boylam: -61.22,
      dosyaboyut: 1236
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fransizguneyveantarktikatopraklari.png",
      enisim: "Frenchsouthernandantarcticlands",
      isim: "Fransizguneyveantarktikatopraklari",
      baskent: "Port-aux-Français",
      kita: "Antarctic",
      url: "https://flagcdn.com/w320/tf.png",
      bilgi: false,
      bm: false,
      enlem: -49.25,
      boylam: 69.17,
      dosyaboyut: 1257
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/peru.png",
      enisim: "Peru",
      isim: "Peru",
      baskent: "Lima",
      kita: "Americas",
      url: "https://flagcdn.com/w320/pe.png",
      bilgi: false,
      bm: true,
      enlem: -10,
      boylam: -76,
      dosyaboyut: 172
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/isvec.png",
      enisim: "Sweden",
      isim: "Isvec",
      baskent: "Stockholm",
      kita: "Europe",
      url: "https://flagcdn.com/w320/se.png",
      bilgi: false,
      bm: true,
      enlem: 62,
      boylam: 15,
      dosyaboyut: 142
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sudan.png",
      enisim: "Sudan",
      isim: "Sudan",
      baskent: "Khartoum",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sd.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: 30,
      dosyaboyut: 744
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/saintpierrevemiquelon.png",
      enisim: "Saintpierreandmiquelon",
      isim: "Saintpierrevemiquelon",
      baskent: "Saint-pierre",
      kita: "Americas",
      url: "https://flagcdn.com/w320/pm.png",
      bilgi: false,
      bm: false,
      enlem: 46.83,
      boylam: -56.33,
      dosyaboyut: 14300
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/umman.png",
      enisim: "Oman",
      isim: "Umman",
      baskent: "Muscat",
      kita: "Asia",
      url: "https://flagcdn.com/w320/om.png",
      bilgi: false,
      bm: true,
      enlem: 21,
      boylam: 57,
      dosyaboyut: 789
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/hindistan.png",
      enisim: "India",
      isim: "Hindistan",
      baskent: "Newdelhi",
      kita: "Asia",
      url: "https://flagcdn.com/w320/in.png",
      bilgi: false,
      bm: true,
      enlem: 20,
      boylam: 77,
      dosyaboyut: 1254
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tayvan.png",
      enisim: "Taiwan",
      isim: "Tayvan",
      baskent: "Taipei",
      kita: "Asia",
      url: "https://flagcdn.com/w320/tw.png",
      bilgi: false,
      bm: false,
      enlem: 23.5,
      boylam: 121,
      dosyaboyut: 1352
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mogolistan.png",
      enisim: "Mongolia",
      isim: "Mogolistan",
      baskent: "Ulanbator",
      kita: "Asia",
      url: "https://flagcdn.com/w320/mn.png",
      bilgi: false,
      bm: true,
      enlem: 46,
      boylam: 105,
      dosyaboyut: 796
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/senegal.png",
      enisim: "Senegal",
      isim: "Senegal",
      baskent: "Dakar",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sn.png",
      bilgi: false,
      bm: true,
      enlem: 14,
      boylam: -14,
      dosyaboyut: 681
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tanzanya.png",
      enisim: "Tanzania",
      isim: "Tanzanya",
      baskent: "Dodoma",
      kita: "Africa",
      url: "https://flagcdn.com/w320/tz.png",
      bilgi: false,
      bm: true,
      enlem: -6,
      boylam: 35,
      dosyaboyut: 1191
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kanada.png",
      enisim: "Canada",
      isim: "Kanada",
      baskent: "Ottawa",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ca.png",
      bilgi: false,
      bm: true,
      enlem: 60,
      boylam: -95,
      dosyaboyut: 1317
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kostarika.png",
      enisim: "Costarica",
      isim: "Kostarika",
      baskent: "SanjosÚ",
      kita: "Americas",
      url: "https://flagcdn.com/w320/cr.png",
      bilgi: false,
      bm: true,
      enlem: 10,
      boylam: -84,
      dosyaboyut: 1665
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cin.png",
      enisim: "China",
      isim: "Cin",
      baskent: "Beijing",
      kita: "Asia",
      url: "https://flagcdn.com/w320/cn.png",
      bilgi: false,
      bm: true,
      enlem: 35,
      boylam: 105,
      dosyaboyut: 955
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kolombiya.png",
      enisim: "Colombia",
      isim: "Kolombiya",
      baskent: "Bogotß",
      kita: "Americas",
      url: "https://flagcdn.com/w320/co.png",
      bilgi: false,
      bm: true,
      enlem: 4,
      boylam: -72,
      dosyaboyut: 231
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/myanmar.png",
      enisim: "Myanmar",
      isim: "Myanmar",
      baskent: "Naypyidaw",
      kita: "Asia",
      url: "https://flagcdn.com/w320/mm.png",
      bilgi: false,
      bm: true,
      enlem: 22,
      boylam: 98,
      dosyaboyut: 1315
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/rusya.png",
      enisim: "Russia",
      isim: "Rusya",
      baskent: "Moscow",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ru.png",
      bilgi: false,
      bm: true,
      enlem: 60,
      boylam: 100,
      dosyaboyut: 153
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kuzeykore.png",
      enisim: "Northkorea",
      isim: "Kuzeykore",
      baskent: "Pyongyang",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kp.png",
      bilgi: false,
      bm: true,
      enlem: 40,
      boylam: 127,
      dosyaboyut: 1133
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/caymanadalari.png",
      enisim: "Caymanislands",
      isim: "Caymanadalari",
      baskent: "Georgetown",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ky.png",
      bilgi: false,
      bm: false,
      enlem: 19.31,
      boylam: -81.25,
      dosyaboyut: 4625
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bouvetadasi.png",
      enisim: "Bouvetisland",
      isim: "Bouvetadasi",
      baskent: "Bouvetadasi",
      kita: "Antarctic",
      url: "https://flagcdn.com/w320/bv.png",
      bilgi: false,
      bm: false,
      enlem: 54.42,
      boylam: 3.35,
      dosyaboyut: 323
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/belarus.png",
      enisim: "Belarus",
      isim: "Belarus",
      baskent: "Minsk",
      kita: "Europe",
      url: "https://flagcdn.com/w320/by.png",
      bilgi: false,
      bm: true,
      enlem: 53,
      boylam: 28,
      dosyaboyut: 1717
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/portekiz.png",
      enisim: "Portugal",
      isim: "Portekiz",
      baskent: "Lisbon",
      kita: "Europe",
      url: "https://flagcdn.com/w320/pt.png",
      bilgi: false,
      bm: true,
      enlem: 39.5,
      boylam: -8,
      dosyaboyut: 4980
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/esvatini.png",
      enisim: "Eswatini",
      isim: "Esvatini",
      baskent: "Mbabane",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sz.png",
      bilgi: false,
      bm: true,
      enlem: -26.5,
      boylam: 31.5,
      dosyaboyut: 2803
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/polonya.png",
      enisim: "Poland",
      isim: "Polonya",
      baskent: "Varşova",
      kita: "Europe",
      url: "https://flagcdn.com/w320/pl.png",
      bilgi: false,
      bm: true,
      enlem: 52,
      boylam: 20,
      dosyaboyut: 119
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/isvicre.png",
      enisim: "Switzerland",
      isim: "Isvicre",
      baskent: "Bern",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ch.png",
      bilgi: false,
      bm: true,
      enlem: 47,
      boylam: 8,
      dosyaboyut: 154
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kongocumhuriyeti.png",
      enisim: "Republicofthecongo",
      isim: "Kongocumhuriyeti",
      baskent: "Brazzaville",
      kita: "Africa",
      url: "https://flagcdn.com/w320/cg.png",
      bilgi: false,
      bm: true,
      enlem: -1,
      boylam: 15,
      dosyaboyut: 980
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/venezuela.png",
      enisim: "Venezuela",
      isim: "Venezuela",
      baskent: "Caracas",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ve.png",
      bilgi: false,
      bm: true,
      enlem: 8,
      boylam: -66,
      dosyaboyut: 906
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/panama.png",
      enisim: "Panama",
      isim: "Panama",
      baskent: "Panamacity",
      kita: "Americas",
      url: "https://flagcdn.com/w320/pa.png",
      bilgi: false,
      bm: true,
      enlem: 9,
      boylam: -80,
      dosyaboyut: 1123
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/hollanda.png",
      enisim: "Netherlands",
      isim: "Hollanda",
      baskent: "Amsterdam",
      kita: "Europe",
      url: "https://flagcdn.com/w320/nl.png",
      bilgi: false,
      bm: true,
      enlem: 52.5,
      boylam: 5.75,
      dosyaboyut: 153
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bagimsizsamoadevleti.png",
      enisim: "Samoa",
      isim: "Bagimsizsamoadevleti",
      baskent: "Apia",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/ws.png",
      bilgi: false,
      bm: true,
      enlem: -13.58,
      boylam: -172.33,
      dosyaboyut: 699
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/danimarka.png",
      enisim: "Denmark",
      isim: "Danimarka",
      baskent: "Copenhagen",
      kita: "Europe",
      url: "https://flagcdn.com/w320/dk.png",
      bilgi: false,
      bm: true,
      enlem: 56,
      boylam: 10,
      dosyaboyut: 292
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/luksemburg.png",
      enisim: "Luxembourg",
      isim: "Luksemburg",
      baskent: "Luxembourg",
      kita: "Europe",
      url: "https://flagcdn.com/w320/lu.png",
      bilgi: false,
      bm: true,
      enlem: 49.75,
      boylam: 6.17,
      dosyaboyut: 151
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/faroeadalari.png",
      enisim: "Faroeislands",
      isim: "Faroeadalari",
      baskent: "Tórshavn",
      kita: "Europe",
      url: "https://flagcdn.com/w320/fo.png",
      bilgi: false,
      bm: false,
      enlem: 62,
      boylam: -7,
      dosyaboyut: 321
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/slovenya.png",
      enisim: "Slovenia",
      isim: "Slovenya",
      baskent: "Lübliyana",
      kita: "Europe",
      url: "https://flagcdn.com/w320/si.png",
      bilgi: false,
      bm: true,
      enlem: 46.12,
      boylam: 14.82,
      dosyaboyut: 930
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/togo.png",
      enisim: "Togo",
      isim: "Togo",
      baskent: "LomÚ",
      kita: "Africa",
      url: "https://flagcdn.com/w320/tg.png",
      bilgi: false,
      bm: true,
      enlem: 8,
      boylam: 1.17,
      dosyaboyut: 751
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tayland.png",
      enisim: "Thailand",
      isim: "Tayland",
      baskent: "Bangkok",
      kita: "Asia",
      url: "https://flagcdn.com/w320/th.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: 100,
      dosyaboyut: 172
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/wallisvefutunaadalaribolgesi.png",
      enisim: "Wallisandfutuna",
      isim: "Wallisvefutunaadalaribolgesi",
      baskent: "Matautu",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/wf.png",
      bilgi: false,
      bm: false,
      enlem: -13.3,
      boylam: -176.2,
      dosyaboyut: 669
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bahamalar.png",
      enisim: "Bahamas",
      isim: "Bahamalar",
      baskent: "Nassau",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bs.png",
      bilgi: false,
      bm: true,
      enlem: 25.03,
      boylam: -77.4,
      dosyaboyut: 735
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tonga.png",
      enisim: "Tonga",
      isim: "Tonga",
      baskent: "Nukualofa",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/to.png",
      bilgi: false,
      bm: true,
      enlem: -20,
      boylam: -175,
      dosyaboyut: 163
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/yunanistan.png",
      enisim: "Greece",
      isim: "Yunanistan",
      baskent: "Athens",
      kita: "Europe",
      url: "https://flagcdn.com/w320/gr.png",
      bilgi: false,
      bm: true,
      enlem: 39,
      boylam: 22,
      dosyaboyut: 306
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sanmarino.png",
      enisim: "Sanmarino",
      isim: "Sanmarino",
      baskent: "San Marino",
      kita: "Europe",
      url: "https://flagcdn.com/w320/sm.png",
      bilgi: false,
      bm: true,
      enlem: 43.77,
      boylam: 12.42,
      dosyaboyut: 7872
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/reunion.png",
      enisim: "Reunion",
      isim: "Reunion",
      baskent: "Saintdenis",
      kita: "Africa",
      url: "https://flagcdn.com/w320/re.png",
      bilgi: false,
      bm: false,
      enlem: -21.15,
      boylam: 55.5,
      dosyaboyut: 2106
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/vatikan.png",
      enisim: "Vaticancity",
      isim: "Vatikan",
      baskent: "Vatikan",
      kita: "Europe",
      url: "https://flagcdn.com/w320/va.png",
      bilgi: false,
      bm: false,
      enlem: 41.9,
      boylam: 12.45,
      dosyaboyut: 7956
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/burundi.png",
      enisim: "Burundi",
      isim: "Burundi",
      baskent: "Gitega",
      kita: "Africa",
      url: "https://flagcdn.com/w320/bi.png",
      bilgi: false,
      bm: true,
      enlem: -3.5,
      boylam: 30,
      dosyaboyut: 1841
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bahreyn.png",
      enisim: "Bahrain",
      isim: "Bahreyn",
      baskent: "Manama",
      kita: "Asia",
      url: "https://flagcdn.com/w320/bh.png",
      bilgi: false,
      bm: true,
      enlem: 26,
      boylam: 50.55,
      dosyaboyut: 827
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/marshalladalari.png",
      enisim: "Marshallislands",
      isim: "Marshalladalari",
      baskent: "Majuro",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/mh.png",
      bilgi: false,
      bm: true,
      enlem: 9,
      boylam: 168,
      dosyaboyut: 2699
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/turksvecaicosadalari.png",
      enisim: "Turksandcaicosislands",
      isim: "Turksvecaicosadalari",
      baskent: "Cockburntown",
      kita: "Americas",
      url: "https://flagcdn.com/w320/tc.png",
      bilgi: false,
      bm: false,
      enlem: 21.75,
      boylam: -71.58,
      dosyaboyut: 2293
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/manadasi.png",
      enisim: "Isleofman",
      isim: "Manadasi",
      baskent: "Douglas",
      kita: "Europe",
      url: "https://flagcdn.com/w320/im.png",
      bilgi: false,
      bm: false,
      enlem: 54.25,
      boylam: -4.5,
      dosyaboyut: 2201
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/haiti.png",
      enisim: "Haiti",
      isim: "Haiti",
      baskent: "Portauprince",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ht.png",
      bilgi: false,
      bm: true,
      enlem: 19,
      boylam: -72.42,
      dosyaboyut: 1972
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/afganistan.png",
      enisim: "Afghanistan",
      isim: "Afganistan",
      baskent: "Kabil",
      kita: "Asia",
      url: "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_the_Taliban.svg/320px-Flag_of_the_Taliban.svg.png",
      bilgi: false,
      bm: true,
      enlem: 33,
      boylam: 65,
      dosyaboyut: 8285
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/israil.png",
      enisim: "Israel",
      isim: "Israil",
      baskent: "Tel Aviv",
      kita: "Asia",
      url: "https://flagcdn.com/w320/il.png",
      bilgi: false,
      bm: true,
      enlem: 31.47,
      boylam: 35.13,
      dosyaboyut: 893
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/libya.png",
      enisim: "Libya",
      isim: "Libya",
      baskent: "Tripoli",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ly.png",
      bilgi: false,
      bm: true,
      enlem: 25,
      boylam: 17,
      dosyaboyut: 579
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/uruguay.png",
      enisim: "Uruguay",
      isim: "Uruguay",
      baskent: "Montevideo",
      kita: "Americas",
      url: "https://flagcdn.com/w320/uy.png",
      bilgi: false,
      bm: true,
      enlem: -33,
      boylam: -56,
      dosyaboyut: 2392
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/norfolkadasi.png",
      enisim: "Norfolkisland",
      isim: "Norfolkadasi",
      baskent: "Kingston",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/nf.png",
      bilgi: false,
      bm: false,
      enlem: -29.03,
      boylam: 167.95,
      dosyaboyut: 2349
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/nikaragua.png",
      enisim: "Nicaragua",
      isim: "Nikaragua",
      baskent: "Managua",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ni.png",
      bilgi: false,
      bm: true,
      enlem: 13,
      boylam: -85,
      dosyaboyut: 1481
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cookadalari.png",
      enisim: "Cookislands",
      isim: "Cookadalari",
      baskent: "Avarua",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/ck.png",
      bilgi: false,
      bm: false,
      enlem: -21.23,
      boylam: -159.77,
      dosyaboyut: 2699
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/laos.png",
      enisim: "Laos",
      isim: "Laos",
      baskent: "Vientiane",
      kita: "Asia",
      url: "https://flagcdn.com/w320/la.png",
      bilgi: false,
      bm: true,
      enlem: 18,
      boylam: 105,
      dosyaboyut: 666
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/christmasadasi.png",
      enisim: "Christmasisland",
      isim: "Christmasadasi",
      baskent: "Flyingfishcove",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/cx.png",
      bilgi: false,
      bm: false,
      enlem: -10.5,
      boylam: 105.67,
      dosyaboyut: 2256
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sainthelena.png",
      enisim: "Sainthelenaascensionandtristandacunha",
      isim: "Sainthelena",
      baskent: "Jamestown",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sh.png",
      bilgi: false,
      bm: false,
      enlem: -15.95,
      boylam: -5.72,
      dosyaboyut: 2484
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/anguilla.png",
      enisim: "Anguilla",
      isim: "Anguilla",
      baskent: "Thevalley",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ai.png",
      bilgi: false,
      bm: false,
      enlem: 18.25,
      boylam: -63.17,
      dosyaboyut: 1929
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mikronezya.png",
      enisim: "Micronesia",
      isim: "Mikronezya",
      baskent: "Palikir",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/fm.png",
      bilgi: false,
      bm: true,
      enlem: 6.92,
      boylam: 158.25,
      dosyaboyut: 676
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/almanya.png",
      enisim: "Germany",
      isim: "Almanya",
      baskent: "Berlin",
      kita: "Europe",
      url: "https://flagcdn.com/w320/de.png",
      bilgi: false,
      bm: true,
      enlem: 51,
      boylam: 9,
      dosyaboyut: 151
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guam.png",
      enisim: "Guam",
      isim: "Guam",
      baskent: "HagÕt±a",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/gu.png",
      bilgi: false,
      bm: false,
      enlem: 13.47,
      boylam: 144.78,
      dosyaboyut: 2205
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/kiribati.png",
      enisim: "Kiribati",
      isim: "Kiribati",
      baskent: "Southtarawa",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/ki.png",
      bilgi: false,
      bm: true,
      enlem: 1.42,
      boylam: 173,
      dosyaboyut: 3872
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sintmaarten.png",
      enisim: "Sintmaarten",
      isim: "Sintmaarten",
      baskent: "Philipsburg",
      kita: "Americas",
      url: "https://flagcdn.com/w320/sx.png",
      bilgi: false,
      bm: false,
      enlem: 18.03,
      boylam: -63.05,
      dosyaboyut: 3972
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ispanya.png",
      enisim: "Spain",
      isim: "Ispanya",
      baskent: "Madrid",
      kita: "Europe",
      url: "https://flagcdn.com/w320/es.png",
      bilgi: false,
      bm: true,
      enlem: 40,
      boylam: -4,
      dosyaboyut: 3623
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/jamaika.png",
      enisim: "Jamaica",
      isim: "Jamaika",
      baskent: "Kingston",
      kita: "Americas",
      url: "https://flagcdn.com/w320/jm.png",
      bilgi: false,
      bm: true,
      enlem: 18.25,
      boylam: -77.5,
      dosyaboyut: 972
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/filistin.png",
      enisim: "Palestine",
      isim: "Filistin",
      baskent: "Ramallahjerusalem",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ps.png",
      bilgi: false,
      bm: false,
      enlem: 31.9,
      boylam: 35.2,
      dosyaboyut: 689
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fransizguyanasi.png",
      enisim: "Frenchguiana",
      isim: "Fransizguyanasi",
      baskent: "Cayenne",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gf.png",
      bilgi: false,
      bm: false,
      enlem: 4,
      boylam: -53,
      dosyaboyut: 1316
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/andorra.png",
      enisim: "Andorra",
      isim: "Andorra",
      baskent: "Andorralavella",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ad.png",
      bilgi: false,
      bm: true,
      enlem: 42.5,
      boylam: 1.5,
      dosyaboyut: 3895
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sili.png",
      enisim: "Chile",
      isim: "Sili",
      baskent: "Santiago",
      kita: "Americas",
      url: "https://flagcdn.com/w320/cl.png",
      bilgi: false,
      bm: true,
      enlem: -30,
      boylam: -71,
      dosyaboyut: 578
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/lesotho.png",
      enisim: "Lesotho",
      isim: "Lesotho",
      baskent: "Maseru",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ls.png",
      bilgi: false,
      bm: true,
      enlem: -29.5,
      boylam: 28.5,
      dosyaboyut: 1065
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/avustralya.png",
      enisim: "Australia",
      isim: "Avustralya",
      baskent: "Canberra",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/au.png",
      bilgi: false,
      bm: true,
      enlem: -27,
      boylam: 133,
      dosyaboyut: 1618
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/grenada.png",
      enisim: "Grenada",
      isim: "Grenada",
      baskent: "Stgeorges",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gd.png",
      bilgi: false,
      bm: true,
      enlem: 12.12,
      boylam: -61.67,
      dosyaboyut: 1950
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gana.png",
      enisim: "Ghana",
      isim: "Gana",
      baskent: "Accra",
      kita: "Africa",
      url: "https://flagcdn.com/w320/gh.png",
      bilgi: false,
      bm: true,
      enlem: 8,
      boylam: -2,
      dosyaboyut: 639
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/seyseller.png",
      enisim: "Seychelles",
      isim: "Seyseller",
      baskent: "Victoria",
      kita: "Africa",
      url: "https://flagcdn.com/w320/sc.png",
      bilgi: false,
      bm: true,
      enlem: -4.58,
      boylam: 55.67,
      dosyaboyut: 1411
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/angola.png",
      enisim: "Angola",
      isim: "Angola",
      baskent: "Luanda",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ao.png",
      bilgi: false,
      bm: true,
      enlem: -12.5,
      boylam: 18.5,
      dosyaboyut: 1581
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/bermuda.png",
      enisim: "Bermuda",
      isim: "Bermuda",
      baskent: "Hamilton",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bm.png",
      bilgi: false,
      bm: false,
      enlem: 32.33,
      boylam: -64.75,
      dosyaboyut: 3942
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/pakistan.png",
      enisim: "Pakistan",
      isim: "Pakistan",
      baskent: "Islamabad",
      kita: "Asia",
      url: "https://flagcdn.com/w320/pk.png",
      bilgi: false,
      bm: true,
      enlem: 30,
      boylam: 70,
      dosyaboyut: 1281
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mali.png",
      enisim: "Mali",
      isim: "Mali",
      baskent: "Bamako",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ml.png",
      bilgi: false,
      bm: true,
      enlem: 17,
      boylam: -4,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/suudiarabistan.png",
      enisim: "Saudiarabia",
      isim: "Suudiarabistan",
      baskent: "Riyadh",
      kita: "Asia",
      url: "https://flagcdn.com/w320/sa.png",
      bilgi: false,
      bm: true,
      enlem: 25,
      boylam: 45,
      dosyaboyut: 3003
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/curacao.png",
      enisim: "Curaao",
      isim: "Curacao",
      baskent: "Willemstad",
      kita: "Americas",
      url: "https://flagcdn.com/w320/cw.png",
      bilgi: false,
      bm: false,
      enlem: 12.12,
      boylam: -68.93,
      dosyaboyut: 643
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guneykore.png",
      enisim: "Southkorea",
      isim: "Guneykore",
      baskent: "Seoul",
      kita: "Asia",
      url: "https://flagcdn.com/w320/kr.png",
      bilgi: false,
      bm: true,
      enlem: 37,
      boylam: 127.5,
      dosyaboyut: 2667
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/etiyopya.png",
      enisim: "Ethiopia",
      isim: "Etiyopya",
      baskent: "Addisababa",
      kita: "Africa",
      url: "https://flagcdn.com/w320/et.png",
      bilgi: false,
      bm: true,
      enlem: 8,
      boylam: 38,
      dosyaboyut: 1887
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/guadeloupe.png",
      enisim: "Guadeloupe",
      isim: "Guadeloupe",
      baskent: "Basseterre",
      kita: "Americas",
      url: "https://flagcdn.com/w320/gp.png",
      bilgi: false,
      bm: false,
      enlem: 16.25,
      boylam: -61.58,
      dosyaboyut: 5294
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/banglades.png",
      enisim: "Bangladesh",
      isim: "Banglades",
      baskent: "Dhaka",
      kita: "Asia",
      url: "https://flagcdn.com/w320/bd.png",
      bilgi: false,
      bm: true,
      enlem: 24,
      boylam: 90,
      dosyaboyut: 807
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/yenizelanda.png",
      enisim: "Newzealand",
      isim: "Yenizelanda",
      baskent: "Wellington",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/nz.png",
      bilgi: false,
      bm: true,
      enlem: -41,
      boylam: 174,
      dosyaboyut: 1564
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/komorlar.png",
      enisim: "Comoros",
      isim: "Komorlar",
      baskent: "Moroni",
      kita: "Africa",
      url: "https://flagcdn.com/w320/km.png",
      bilgi: false,
      bm: true,
      enlem: -12.17,
      boylam: 44.25,
      dosyaboyut: 1587
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/belize.png",
      enisim: "Belize",
      isim: "Belize",
      baskent: "Belmopan",
      kita: "Americas",
      url: "https://flagcdn.com/w320/bz.png",
      bilgi: false,
      bm: true,
      enlem: 17.25,
      boylam: -88.75,
      dosyaboyut: 6797
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/uganda.png",
      enisim: "Uganda",
      isim: "Uganda",
      baskent: "Kampala",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ug.png",
      bilgi: false,
      bm: true,
      enlem: 1,
      boylam: 32,
      dosyaboyut: 1457
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/singapur.png",
      enisim: "Singapore",
      isim: "Singapur",
      baskent: "Singapore",
      kita: "Asia",
      url: "https://flagcdn.com/w320/sg.png",
      bilgi: false,
      bm: true,
      enlem: 1.37,
      boylam: 103.8,
      dosyaboyut: 974
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/lihtenstayn.png",
      enisim: "Liechtenstein",
      isim: "Lihtenstayn",
      baskent: "Vaduz",
      kita: "Europe",
      url: "https://flagcdn.com/w320/li.png",
      bilgi: false,
      bm: true,
      enlem: 47.27,
      boylam: 9.53,
      dosyaboyut: 1336
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/macaristan.png",
      enisim: "Hungary",
      isim: "Macaristan",
      baskent: "Budapeşte",
      kita: "Europe",
      url: "https://flagcdn.com/w320/hu.png",
      bilgi: false,
      bm: true,
      enlem: 47,
      boylam: 20,
      dosyaboyut: 199
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/izlanda.png",
      enisim: "Iceland",
      isim: "Izlanda",
      baskent: "Reykjavik",
      kita: "Europe",
      url: "https://flagcdn.com/w320/is.png",
      bilgi: false,
      bm: true,
      enlem: 65,
      boylam: -18,
      dosyaboyut: 330
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/tacikistan.png",
      enisim: "Tajikistan",
      isim: "Tacikistan",
      baskent: "Dushanbe",
      kita: "Asia",
      url: "https://flagcdn.com/w320/tj.png",
      bilgi: false,
      bm: true,
      enlem: 39,
      boylam: 71,
      dosyaboyut: 874
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/namibya.png",
      enisim: "Namibia",
      isim: "Namibya",
      baskent: "Windhoek",
      kita: "Africa",
      url: "https://flagcdn.com/w320/na.png",
      bilgi: false,
      bm: true,
      enlem: -22,
      boylam: 17,
      dosyaboyut: 1896
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/dogutimor.png",
      enisim: "Timorleste",
      isim: "Dogutimor",
      baskent: "Dili",
      kita: "Asia",
      url: "https://flagcdn.com/w320/tl.png",
      bilgi: false,
      bm: true,
      enlem: -8.83,
      boylam: 125.92,
      dosyaboyut: 1305
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/misir.png",
      enisim: "Egypt",
      isim: "Misir",
      baskent: "Kahire",
      kita: "Africa",
      url: "https://flagcdn.com/w320/eg.png",
      bilgi: false,
      bm: true,
      enlem: 27,
      boylam: 30,
      dosyaboyut: 1198
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/sirbistan.png",
      enisim: "Serbia",
      isim: "Sirbistan",
      baskent: "Belgrade",
      kita: "Europe",
      url: "https://flagcdn.com/w320/rs.png",
      bilgi: false,
      bm: true,
      enlem: 44,
      boylam: 21,
      dosyaboyut: 6204
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/mauritius.png",
      enisim: "Mauritius",
      isim: "Mauritius",
      baskent: "Portlouis",
      kita: "Africa",
      url: "https://flagcdn.com/w320/mu.png",
      bilgi: false,
      bm: true,
      enlem: -20.28,
      boylam: 57.55,
      dosyaboyut: 245
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/makao.png",
      enisim: "Macau",
      isim: "Makao",
      baskent: "Makao",
      kita: "Asia",
      url: "https://flagcdn.com/w320/mo.png",
      bilgi: false,
      bm: false,
      enlem: 22.17,
      boylam: 113.55,
      dosyaboyut: 2255
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/fransizpolinezyasi.png",
      enisim: "Frenchpolynesia",
      isim: "Fransizpolinezyasi",
      baskent: "Papeete",
      kita: "Oceania",
      url: "https://flagcdn.com/w320/pf.png",
      bilgi: false,
      bm: false,
      enlem: 17.68,
      boylam: 149.41,
      dosyaboyut: 2561
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/maldivler.png",
      enisim: "Maldives",
      isim: "Maldivler",
      baskent: "Male",
      kita: "Asia",
      url: "https://flagcdn.com/w320/mv.png",
      bilgi: false,
      bm: true,
      enlem: 3.25,
      boylam: 73,
      dosyaboyut: 704
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/endonezya.png",
      enisim: "Indonesia",
      isim: "Endonezya",
      baskent: "Jakarta",
      kita: "Asia",
      url: "https://flagcdn.com/w320/id.png",
      bilgi: false,
      bm: true,
      enlem: -5,
      boylam: 120,
      dosyaboyut: 146
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/demokratikkongocumhuriyeti.png",
      enisim: "Drcongo",
      isim: "Demokratikkongocumhuriyeti",
      baskent: "Kinshasa",
      kita: "Africa",
      url: "https://flagcdn.com/w320/cd.png",
      bilgi: false,
      bm: true,
      enlem: 0,
      boylam: 25,
      dosyaboyut: 1486
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/estonya.png",
      enisim: "Estonia",
      isim: "Estonya",
      baskent: "Tallinn",
      kita: "Europe",
      url: "https://flagcdn.com/w320/ee.png",
      bilgi: false,
      bm: true,
      enlem: 59,
      boylam: 26,
      dosyaboyut: 153
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/vietnam.png",
      enisim: "Vietnam",
      isim: "Vietnam",
      baskent: "Hanoi",
      kita: "Asia",
      url: "https://flagcdn.com/w320/vn.png",
      bilgi: false,
      bm: true,
      enlem: 16.17,
      boylam: 107.83,
      dosyaboyut: 913
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/italya.png",
      enisim: "Italy",
      isim: "Italya",
      baskent: "Rome",
      kita: "Europe",
      url: "https://flagcdn.com/w320/it.png",
      bilgi: false,
      bm: true,
      enlem: 42.83,
      boylam: 12.83,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gine.png",
      enisim: "Guinea",
      isim: "Gine",
      baskent: "Conakry",
      kita: "Africa",
      url: "https://flagcdn.com/w320/gn.png",
      bilgi: false,
      bm: true,
      enlem: 11,
      boylam: -10,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/cad.png",
      enisim: "Chad",
      isim: "Cad",
      baskent: "Ndjamena",
      kita: "Africa",
      url: "https://flagcdn.com/w320/td.png",
      bilgi: false,
      bm: true,
      enlem: 15,
      boylam: 19,
      dosyaboyut: 253
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/ekvador.png",
      enisim: "Ecuador",
      isim: "Ekvador",
      baskent: "Quito",
      kita: "Americas",
      url: "https://flagcdn.com/w320/ec.png",
      bilgi: false,
      bm: true,
      enlem: -2,
      boylam: -77.5,
      dosyaboyut: 5052
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gurcistan.png",
      enisim: "Georgia",
      isim: "Gurcistan",
      baskent: "Tbilisi",
      kita: "Asia",
      url: "https://flagcdn.com/w320/ge.png",
      bilgi: false,
      bm: true,
      enlem: 42,
      boylam: 43.5,
      dosyaboyut: 1046
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/malavi.png",
      enisim: "Malawi",
      isim: "Malavi",
      baskent: "Lilongwe",
      kita: "Africa",
      url: "https://flagcdn.com/w320/mw.png",
      bilgi: false,
      bm: true,
      enlem: -13.5,
      boylam: 34,
      dosyaboyut: 1467
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/irak.png",
      enisim: "Iraq",
      isim: "Irak",
      baskent: "Baghdad",
      kita: "Asia",
      url: "https://flagcdn.com/w320/iq.png",
      bilgi: false,
      bm: true,
      enlem: 33,
      boylam: 44,
      dosyaboyut: 789
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/svalbardvejanmayen.png",
      enisim: "Svalbardandjanmayen",
      isim: "Svalbardvejanmayen",
      baskent: "Longyearbyen",
      kita: "Europe",
      url: "https://flagcdn.com/w320/sj.png",
      bilgi: false,
      bm: false,
      enlem: 78,
      boylam: 20,
      dosyaboyut: 323
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/benin.png",
      enisim: "Benin",
      isim: "Benin",
      baskent: "Portonovo",
      kita: "Africa",
      url: "https://flagcdn.com/w320/bj.png",
      bilgi: false,
      bm: true,
      enlem: 9.5,
      boylam: 2.25,
      dosyaboyut: 176
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/japonya.png",
      enisim: "Japan",
      isim: "Japonya",
      baskent: "Tokyo",
      kita: "Asia",
      url: "https://flagcdn.com/w320/jp.png",
      bilgi: false,
      bm: true,
      enlem: 36,
      boylam: 138,
      dosyaboyut: 932
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/dominikcumhuriyeti.png",
      enisim: "Dominicanrepublic",
      isim: "Dominikcumhuriyeti",
      baskent: "Santodomingo",
      kita: "Americas",
      url: "https://flagcdn.com/w320/do.png",
      bilgi: false,
      bm: true,
      enlem: 19,
      boylam: -70.67,
      dosyaboyut: 1658
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/katar.png",
      enisim: "Qatar",
      isim: "Katar",
      baskent: "Doha",
      kita: "Asia",
      url: "https://flagcdn.com/w320/qa.png",
      bilgi: false,
      bm: true,
      enlem: 25.5,
      boylam: 51.25,
      dosyaboyut: 336
  ),
  Ulkeler(
      bayrak: "assets/bayraklar/gabon.png",
      enisim: "Gabon",
      isim: "Gabon",
      baskent: "Libreville",
      kita: "Africa",
      url: "https://flagcdn.com/w320/ga.png",
      bilgi: false,
      bm: true,
      enlem: -1,
      boylam: 11.75,
      dosyaboyut: 161
  ),
];
